src/ViewModels/ModelBindingSimpleVM.cs
using System.ComponentModel;

namespace MvcConventions.ViewModels
{
    public class ModelBindingSimpleVM
    {
        [DisplayName("Name : ")]
        public string Name { get; set; }

        [DisplayName("Age : ")]
        public int Age { get; set; }
    }
}

src/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcConventions.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

src/Controllers/ModelBindingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MvcConventions.ViewModels;

namespace MvcConventions.Controllers
{
    public class ModelBindingController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SimpleValue(int id = 0)
        {
            ViewBag.Number = ConvertNumberToWords(id);
            
            return View(id);
        }
        
        #region Simple Object Model binding
        
        [HttpGet]
        public ActionResult SimpleObject()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SimpleObject(ModelBindingSimpleVM vm)
        {
            TempData["simple"] = vm;

            return RedirectToAction("SimpleObjectResult");
        }

        [HttpGet]
        public ActionResult SimpleObjectResult()
        {
            var vm = TempData["simple"] as ModelBindingSimpleVM;
            return View(vm);
        } 

        #endregion

        #region Private

        private string ConvertNumberToWords(int id)
        {
            if (id > 10)
            {
                return "";
            }

            string[] numbersToLetters = { "", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten" };

            return numbersToLetters[id];
        }

        #endregion
    }
}

src/Controllers/ReferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcConventions.Controllers
{
    public class ReferenceController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

src/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Home Index Page</h2>

src/Views/ModelBinding/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Model Binding Examples</h2>


@Html.ActionLink("Simple Value", "SimpleValue")<br/>
@Html.ActionLink("Simple Object", "SimpleObject")

src/Views/ModelBinding/SimpleObject.cshtml
@model MvcConventions.ViewModels.ModelBindingSimpleVM
@{
    ViewBag.Title = "SimpleObject";
}

<h2>Example Simple</h2>

@using (Html.BeginForm())
{
    @Html.LabelFor(m => m.Name)
    @Html.EditorFor(m => m.Name)
    <br />

    @Html.LabelFor(m => m.Age)
    @Html.EditorFor(m => m.Age)
    <br />
    
    <input type="submit"/>
}

src/Views/ModelBinding/SimpleObjectResult.cshtml
@model MvcConventions.ViewModels.ModelBindingSimpleVM
@{
    ViewBag.Title = "SimpleObjectResult";
}

<h2>SimpleObjectResult</h2>

@Html.DisplayForModel()

src/Views/ModelBinding/SimpleValue.cshtml
@model System.Int32

@{
    ViewBag.Title = "SimpleValue";
}

<h2>Simple Value</h2>

@if (ViewBag.Number != null)
{
    <text>Result: </text> @ViewBag.Number
}

<ul>
    @for (var i = 1; i < 11; i++)
    {
        <li>
            @if (i == Model)
            {
                @i               
            }
            else
            {
                <span>Id </span>
                @Html.ActionLink(i.ToString(), "SimpleValue", new {@id = i})
                
                <span>myId </span>
                @Html.ActionLink(i.ToString(), "SimpleValue", new {@myId = i})
            }
        </li>
    }    
</ul>

src/Views/Reference/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Reference</h2>

src/Views/Shared/DisplayTemplates/ModelBindingSimpleVM.cshtml
@model MvcConventions.ViewModels.ModelBindingSimpleVM

@Model.Name is @Model.Age years old.

src/Views/Shared/NavigationLinks.cshtml
<ul>
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Model Binding", "Index", "ModelBinding")
    </li>
    <li>
        @Html.ActionLink("Reference", "Index", "Reference")
    </li>
</ul>

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
    <body>
        @Html.Partial("NavigationLinks")

        @RenderBody()

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>